#!/bin/bash


usage()
{
  echo "Usage: gitcommit -b <branch> -m <message>"
  exit 1
}

while getopts "b:m:" opt ; do
  case "$opt" in
    m)
    message="$OPTARG"
    ;;
    b)
    branch="$OPTARG"
    ;;
    *)
    usage
    ;;
  esac
done

if [ -z "$message" ] || [ -z "$branch" ]; then
  usage
fi

git add --all;

git commit -m "$message";

git push origin $branch;
